In [1]:
import requests
import pandas as pd

In [3]:
from getpass import getpass

api_key = getpass("Enter your TMDB API key: ")
df_list = []

for i in range(1, 501):
    
    url = "https://api.themoviedb.org/3/discover/movie?api_key={}&language=en-US&page={}".format(api_key, i)
    
    response = requests.get(url)
    response.raise_for_status()

    temp_df = pd.DataFrame(response.json()['results'])

    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

Enter your TMDB API key:  ········

## Data Preview

In [5]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,839.8698,/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg,2026-07-29,False,False,7.861,2541
1,False,/l9mFW9HQnAZ4r1ChZJHoOT3jaal.jpg,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,After Acme products fail him one too many time...,643.9483,/orkLtdgMGiO9rTVMqJ1kKwrnup1.jpg,2026-08-20,False,False,7.663,264
2,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",437.8516,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,8.000,3565
3,False,/e2QAGrEmbpmZpMymDRkDisJkvg9.jpg,"[28, 53]",1288445,Mutiny,en,Mutiny,After witnessing his billionaire boss' murder ...,394.5615,/pu2VxGlpGwffOx292w18b1tv96j.jpg,2026-08-19,False,False,6.359,334
4,False,/hpBGCnzOvdtQoMyE48gvwp2y5yx.jpg,"[28, 27, 878]",1375646,Colony,ko,군체,Professor Se-jeong is thrust into a bloody nig...,315.0795,/tN799oUR0f1gUKDYdMNrDaY7I51.jpg,2026-05-21,False,False,8.113,729

In [7]:
df.shape

(10000, 15)

In [9]:
df.dtypes

adult                   bool
backdrop_path            str
genre_ids             object
id                     int64
title                    str
original_language        str
original_title           str
overview                 str
popularity           float64
poster_path              str
release_date             str
softcore                bool
video                   bool
vote_average         float64
vote_count             int64
dtype: object

In [11]:
df.describe()

                 id    popularity  vote_average    vote_count
count  1.000000e+04  10000.000000  10000.000000  10000.000000
mean   4.446535e+05      9.163763      6.000066   1975.134400
std    4.954943e+05     16.055434      2.162340   3519.657005
min    5.000000e+00      1.921400      0.000000      0.000000
25%    1.190325e+04      5.172525      5.838750     33.000000
50%    2.906940e+05      6.343450      6.538000    755.000000
75%    7.436445e+05      9.128350      7.174000   2195.250000
max    1.765072e+06    839.869800     10.000000  41098.000000

In [15]:
df["id"].duplicated().sum()

222

In [17]:
df["id"].is_unique

False

In [21]:
df = df.drop_duplicates(subset="id", keep="first")

In [23]:
print("Rows after removing duplicates:", len(df))
print("Duplicate IDs:", df["id"].duplicated().sum())

Rows after removing duplicates: 9778
Duplicate IDs: 0

In [25]:
df[df["poster_path"].isna()].head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
1663,False,NaN,[99],931908,Cyclotron,en,Cyclotron,A film about the world's oldest functional par...,11.5692,NaN,2020-09-16,False,False,0.0,0
1891,False,NaN,[10751],414947,Assume Yourself,hu,Vállald önmagadat,A story about the Hungarian pioneers summer va...,12.2624,NaN,1975-02-20,False,False,8.5,2
2046,False,NaN,[10749],1461238,Deep in My Heart,cn,長相憶,Overseas student Zheng Yihua and her native Ko...,9.7376,NaN,1967-12-10,False,False,0.0,0
2182,False,NaN,"[53, 27]",328688,Orang Minyak,ms,Orang Minyak,This story is based on fiction and myth made b...,12.4107,NaN,2007-11-15,False,False,0.0,0
2322,False,NaN,[18],388375,Se Não...,pt,Se Não...,,12.2178,NaN,2015-04-25,False,False,10.0,1

In [27]:
df[df["backdrop_path"].isna()].head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
70,False,NaN,[],1494843,丫丫,zh,丫丫,,54.5908,/yw74ajOTn9SG1wbDao62IVf7VlW.jpg,1979-03-01,False,False,0.0,0
74,False,NaN,[27],687259,Ghost Stories,zh,镜花风月三之螺女挑情,,52.9698,/m4ALMhsuqOOUkkABvgQWfrgoL8y.jpg,1982-01-01,False,False,6.2,2
131,False,NaN,[10749],895954,母女汽车中心,ko,莫尼卡中心,"Yeon Ja, a working mother, runs a car center a...",33.3101,/saca8CL9kk22AS5BfMbwSYgMvdp.jpg,2021-01-01,False,False,4.0,1
157,False,NaN,[18],89657,Country Hooker,en,Country Hooker,A couple of musicians are on their way to a sh...,40.7895,/xNb6s2uCSv7PnLyNyqAGAmmI3Fk.jpg,1974-10-04,False,False,3.9,7
161,False,NaN,[],1156869,Blaze of Love,en,性迷宮,Hong Kong movie,40.9789,/cSOW4av17KfO9K2CRqKCjMbeoMw.jpg,1994-01-01,False,False,0.0,0

In [29]:
df["release_date"] = pd.to_datetime(df["release_date"])

In [31]:
df["release_date"].dtype

dtype('<M8[us]')

In [33]:
df[["id", "title", "adult", "video", "softcore"]].head(5)

        id                      title  adult  video  softcore
0   969681  Spider-Man: Brand New Day  False  False     False
1  1204680            Coyote vs. Acme  False  False     False
2  1368337                The Odyssey  False  False     False
3  1288445                     Mutiny  False  False     False
4  1375646                     Colony  False  False     False

In [35]:
df[["adult", "video", "softcore"]].value_counts()

adult  video  softcore
False  False  False       9778
Name: count, dtype: int64

In [37]:
df = df.drop(columns=["adult", "video", "softcore"])

In [39]:
df.shape

(9778, 12)

In [43]:
df = df.drop(columns=["poster_path", "backdrop_path"])

In [89]:
df = df.drop(columns=["overview"])

In [91]:
df.isnull().sum()

genre_ids               0
id                      0
title                   0
original_language       0
original_title          0
popularity              0
release_date           80
vote_average            0
vote_count              0
release_date_status     0
dtype: int64

In [93]:
df[df["release_date"].isna()]

,genre_ids,id,title,original_language,original_title,popularity,release_date,vote_average,vote_count,release_date_status
171,"[16, 28, 12, 14]",1599191,Renegade Immortal: Battle of the Immortal Slayer,zh,仙逆剧场版：弑仙之战,29.5754,NaT,0.0,0,Unknown
2123,"[10749, 18]",1128879,Mil Kilómetros,es,Mil Kilómetros,7.0823,NaT,0.0,0,Unknown
2360,[],826046,Ramon Alvarado,en,Ramon Alvarado,10.7915,NaT,0.0,0,Unknown
2721,[18],1757000,Gorgeous Grandmother,tl,Gandang Lola,7.9649,NaT,0.0,0,Unknown
2791,"[28, 18]",1702400,School Bus,ta,School Bus,9.0324,NaT,0.0,0,Unknown
...,...,...,...,...,...,...,...,...,...,...
9753,"[27, 9648]",1749553,The Projectionist,fr,Le Projectionniste,4.8462,NaT,0.0,0,Unknown
9790,"[35, 18, 27]",1753358,Two Waiters,en,Two Waiters,4.6043,NaT,0.0,0,Unknown
9905,[],1328682,La Nota,es,La Nota,3.9273,NaT,0.0,0,Unknown
9914,[99],1392233,Aura Roja,es,Aura Roja,5.6436,NaT,0.0,0,Unknown
9958,"[80, 28]",702949,Say Goodbye!,pt,Say Goodbye!,4.7332,NaT,10.0,2,Unknown

In [95]:
df[df["release_date"].isna()][["id", "title", "release_date"]].head(10)

           id                                             title release_date
171   1599191  Renegade Immortal: Battle of the Immortal Slayer          NaT
2123  1128879                                    Mil Kilómetros          NaT
2360   826046                                    Ramon Alvarado          NaT
2721  1757000                              Gorgeous Grandmother          NaT
2791  1702400                                        School Bus          NaT
3184   843271                                       French Film          NaT
3261   413387                                           As Três          NaT
3394  1755121                                           Therapy          NaT
3952  1755103                                           Mom IRL          NaT
4168  1757605                                              Seen          NaT

In [97]:
df["release_date_status"] = df["release_date"].isna().map({
    True: "Unknown",
    False: "Available"
})

In [99]:
df.dtypes

genre_ids                      object
id                              int64
title                             str
original_language                 str
original_title                    str
popularity                    float64
release_date           datetime64[us]
vote_average                  float64
vote_count                      int64
release_date_status               str
dtype: object

In [101]:
print("Minimum rating:", df["vote_average"].min())
print("Maximum rating:", df["vote_average"].max())

Minimum rating: 0.0
Maximum rating: 10.0

In [103]:
(df["vote_count"] < 0).sum()

0

In [105]:
(df["popularity"] < 0).sum()

0

In [107]:
(df["title"].str.strip() == "").sum()

0

In [127]:
(df["title"].str.strip() == "").sum()

0

In [125]:
df

,genre_ids,id,title,original_language,original_title,popularity,release_date,vote_average,vote_count,release_date_status
0,"[878, 28, 12]",969681,Spider-Man: Brand New Day,en,Spider-Man: Brand New Day,839.8698,2026-07-29,7.861,2541,Available
1,"[35, 12, 10751]",1204680,Coyote vs. Acme,en,Coyote vs. Acme,643.9483,2026-08-20,7.663,264,Available
2,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,437.8516,2026-07-15,8.000,3565,Available
3,"[28, 53]",1288445,Mutiny,en,Mutiny,394.5615,2026-08-19,6.359,334,Available
4,"[28, 27, 878]",1375646,Colony,ko,군체,315.0795,2026-05-21,8.113,729,Available
...,...,...,...,...,...,...,...,...,...,...
9995,[35],11305,Mystery Train,en,Mystery Train,4.4336,1989-09-06,7.300,532,Available
9996,"[12, 18, 36]",739986,True Spirit,en,True Spirit,3.8592,2023-01-26,6.996,271,Available
9997,[18],143655,Female Convict 101: Suck,ja,女囚101 しゃぶる,3.9161,1977-08-06,4.813,8,Available
9998,"[16, 9648, 28, 80]",736073,"Batman: The Long Halloween, Part One",en,"Batman: The Long Halloween, Part One",4.6472,2021-06-21,7.445,723,Available
9999,"[35, 10749]",11823,Wimbledon,en,Wimbledon,4.0921,2004-09-13,6.230,1101,Available

In [111]:
df.shape

(9778, 10)

In [113]:
df.isnull().sum()

genre_ids               0
id                      0
title                   0
original_language       0
original_title          0
popularity              0
release_date           80
vote_average            0
vote_count              0
release_date_status     0
dtype: int64

In [117]:
df.dtypes

genre_ids                      object
id                              int64
title                             str
original_language                 str
original_title                    str
popularity                    float64
release_date           datetime64[us]
vote_average                  float64
vote_count                      int64
release_date_status               str
dtype: object

In [135]:
df.to_csv("movies_clean.csv", index=False)

In [137]:
import mysql.connector

In [139]:
from getpass import getpass

password = getpass("Enter MySQL Password: ")

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password=password,
)

Enter MySQL Password:  ········

In [143]:
print(conn.is_connected())

True

In [147]:
cursor = conn.cursor()

cursor.execute("CREATE DATABASE IF NOT EXISTS movie_analytics")

print("Database ready")

Database ready

In [149]:
cursor.close()
conn.close()

In [151]:
from getpass import getpass

password = getpass("Enter MySQL Password: ")

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password=password,
    database="movie_analytics"
)
cursor = conn.cursor()

Enter MySQL Password:  ········

In [155]:
create_table_query = """
CREATE TABLE IF NOT EXISTS movies (
    id INT PRIMARY KEY,
    title VARCHAR(500),
    original_language VARCHAR(20),
    original_title VARCHAR(500),
    popularity DOUBLE,
    release_date DATE NULL,
    vote_average DOUBLE,
    vote_count INT,
    release_date_status VARCHAR(20),
    genre_ids TEXT
)
"""

cursor.execute(create_table_query)
conn.commit()

print("Movies table created")

Movies table created

In [157]:
import json

df["genre_ids"] = df["genre_ids"].apply(json.dumps)

In [159]:
print(df["genre_ids"].iloc[0])
print(type(df["genre_ids"].iloc[0]))

[878, 28, 12]
<class 'str'>

In [161]:
data = df[
    [
        "id",
        "title",
        "original_language",
        "original_title",
        "popularity",
        "release_date",
        "vote_average",
        "vote_count",
        "release_date_status",
        "genre_ids"
    ]
].values.tolist()

In [163]:
print(len(data))
print(data[0])

9778
[969681, 'Spider-Man: Brand New Day', 'en', 'Spider-Man: Brand New Day', 839.8698, Timestamp('2026-07-29 00:00:00'), 7.861, 2541, 'Available', '[878, 28, 12]']

In [165]:
insert_query = """
INSERT INTO movies (
    id,
    title,
    original_language,
    original_title,
    popularity,
    release_date,
    vote_average,
    vote_count,
    release_date_status,
    genre_ids
)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [167]:
cursor.executemany(insert_query, data)
conn.commit()

print("Data inserted successfully!")

ProgrammingError: Failed processing format-parameters; Unknown format code 'd' for object of type 'float'

In [169]:
df["release_date"] = df["release_date"].where(
    df["release_date"].notna(),
    None
)

In [171]:
data = []

for row in df.itertuples(index=False):
    data.append((
        int(row.id),
        row.title,
        row.original_language,
        row.original_title,
        float(row.popularity),
        row.release_date.date() if pd.notna(row.release_date) else None,
        float(row.vote_average),
        int(row.vote_count),
        row.release_date_status,
        row.genre_ids
    ))

In [173]:
print(len(data))
print(data[0])

9778
(969681, 'Spider-Man: Brand New Day', 'en', 'Spider-Man: Brand New Day', 839.8698, datetime.date(2026, 7, 29), 7.861, 2541, 'Available', '[878, 28, 12]')

In [175]:
cursor.executemany(insert_query, data)
conn.commit()

print("Data inserted successfully!")

Data inserted successfully!

In [177]:
cursor.execute("SELECT COUNT(*) FROM movies")

count = cursor.fetchone()[0]

print("Movies in SQL:", count)

Movies in SQL: 9778

In [179]:
cursor.execute("""
SELECT 
    id,
    title,
    original_language,
    release_date,
    popularity,
    vote_average,
    vote_count
FROM movies
LIMIT 10
""")

rows = cursor.fetchall()

for row in rows:
    print(row)

(5, 'Four Rooms', 'en', datetime.date(1995, 12, 9), 5.8893, 5.918, 2901)
(6, 'Judgment Night', 'en', datetime.date(1993, 10, 15), 4.9007, 6.448, 387)
(11, 'Star Wars', 'en', datetime.date(1977, 5, 25), 31.856, 8.207, 22831)
(12, 'Finding Nemo', 'en', datetime.date(2003, 5, 30), 31.314, 7.821, 20947)
(13, 'Forrest Gump', 'en', datetime.date(1994, 6, 23), 33.6938, 8.462, 30412)
(14, 'American Beauty', 'en', datetime.date(1999, 9, 15), 16.9277, 7.996, 13323)
(15, 'Citizen Kane', 'en', datetime.date(1941, 4, 17), 12.1148, 7.968, 6214)
(16, 'Dancer in the Dark', 'en', datetime.date(2000, 9, 1), 5.1968, 7.837, 2063)
(18, 'The Fifth Element', 'fr', datetime.date(1997, 5, 2), 21.093, 7.59, 12114)
(19, 'Metropolis', 'de', datetime.date(1927, 1, 10), 9.9267, 8.085, 3188)

In [181]:
cursor.execute("""
SELECT COUNT(*)
FROM movies
WHERE release_date IS NULL
""")

print("Missing release dates:", cursor.fetchone()[0])

Missing release dates: 80

In [183]:
cursor.close()
conn.close()

In [185]:
print(conn.is_connected())

False